### ISSUE TITLE
Fixed Sentence/Length RAG implemented incorrectly

### ISSUE THREAD

**Issue by TanmayParekh** [oneal2000/DRAGIN#10]
Referring to this line - https://github.com/oneal2000/DRAGIN/blob/a924d14f6f16210dc9edab1774f6567428eb1b52/src/generate.py#L272

It seems that fixed sentence/length RAG simply retrieve based on the question instead of the latest generation. This is in contradiction to what's mentioned in the paper.

**Comment by oneal2000** [comment]
Thank you for pointing this out, we have just fixed this bug.
