### ISSUE TITLE
Previous context incorrectly computed

### ISSUE THREAD

**Issue by TanmayParekh** [oneal2000/DRAGIN#12]
Linking lines:

https://github.com/oneal2000/DRAGIN/blob/7e4ac6f43c4ce5a7e6bf5b41246f12aa59468f10/src/generate.py#L333

https://github.com/oneal2000/DRAGIN/blob/7e4ac6f43c4ce5a7e6bf5b41246f12aa59468f10/src/generate.py#L462

https://github.com/oneal2000/DRAGIN/blob/7e4ac6f43c4ce5a7e6bf5b41246f12aa59468f10/src/generate.py#L520

I think it should be `sentences[:sid]` and not `sentences[:sid-1]` as is now

**Comment by Bocchi7** [comment]
Fixed. Thank you!
